# Generated by Django 6.0.4 on 2026-05-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_perfilusuario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_finanzas_category_usuario_nombre_tipo',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('nombre', 'tipo'), name='uniq_finanzas_category_nombre_tipo'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='usuario',
        ),
    ]
