# Generated by Django 6.0.4 on 2026-07-02 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_perfilusuario_estado_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('monto_rapido', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta de ahorro',
                'verbose_name_plural': 'Metas de ahorro',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='chk_transaction_origen',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tipo',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('saving', 'Ahorro')], max_length=10),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='categoria_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_referencia', to='finanzas.category'),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='finanzas.metaahorro'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categoria__isnull', False), ('meta__isnull', True), ('presupuesto__isnull', True), ('tipo', 'income')), models.Q(('categoria__isnull', True), ('meta__isnull', True), ('presupuesto__isnull', False), ('recurrente__isnull', True), ('tipo', 'expense')), models.Q(('categoria__isnull', False), ('meta__isnull', True), ('presupuesto__isnull', True), ('recurrente__isnull', True), ('tipo', 'expense')), models.Q(('categoria__isnull', False), ('meta__isnull', True), ('presupuesto__isnull', True), ('recurrente__isnull', False), ('tipo', 'expense')), models.Q(('categoria__isnull', True), ('meta__isnull', False), ('presupuesto__isnull', True), ('recurrente__isnull', True), ('tipo', 'saving')), _connector='OR'), name='chk_transaction_origen'),
        ),
        migrations.AddConstraint(
            model_name='metaahorro',
            constraint=models.CheckConstraint(condition=models.Q(('monto_objetivo__gt', 0)), name='chk_meta_monto_objetivo_mayor_que_cero'),
        ),
        migrations.AddConstraint(
            model_name='metaahorro',
            constraint=models.CheckConstraint(condition=models.Q(('monto_rapido__gt', 0)), name='chk_meta_monto_rapido_mayor_que_cero'),
        ),
    ]
