# Generated by Django 6.0.4 on 2026-07-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_preferenciasusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaahorro',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurrente',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurrente',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
