# Generated by Django 6.0.4 on 2026-08-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_metaahorro_fecha_inicio_recurrente_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='limitar_saldo_negativo',
            field=models.BooleanField(default=False),
        ),
    ]
