# Generated by Django 6.0.4 on 2026-08-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_preferenciasusuario_limitar_saldo_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='permitir_asignacion_directa_metas',
            field=models.BooleanField(default=False),
        ),
    ]
