# Generated by Django 6.0.4 on 2026-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_preferenciasusuario_permitir_asignacion_directa_metas'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaahorro',
            name='es_asignacion_libre',
            field=models.BooleanField(default=False),
        ),
    ]
