# Generated by Django 6.0.4 on 2026-08-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_metaahorro_es_asignacion_libre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenteAjusteMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes del ajuste (YYYY-MM-01)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_mes', to='finanzas.recurrente')),
            ],
            options={
                'verbose_name': 'Ajuste mensual de recurrente',
                'verbose_name_plural': 'Ajustes mensuales de recurrentes',
                'ordering': ['-mes'],
                'constraints': [models.UniqueConstraint(fields=('recurrente', 'mes'), name='uniq_recurrente_ajuste_mes'), models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_recurrente_ajuste_mes_monto_gt_zero')],
            },
        ),
    ]
