# Generated by Django 6.0.4 on 2026-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_recurrenteajustemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrenteajustemes',
            name='permite_parciales',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
