# Generated by Django 6.0.4 on 2026-09-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_recurrenteajustemes_permite_parciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_cuenta',
            field=models.CharField(choices=[('basico', 'Básico'), ('avanzado', 'Avanzado')], default='basico', max_length=15),
        ),
    ]
