# Generated by Django 6.0.4 on 2026-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_perfilusuario_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='descontar_ahorros_balance',
            field=models.BooleanField(default=False),
        ),
    ]
