# Generated by Django 6.0.4 on 2026-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0018_preferenciasusuario_descontar_ahorros_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_expiracion',
            field=models.DateField(blank=True, help_text='Fecha límite de acceso. Null significa acceso permanente.', null=True),
        ),
    ]
