# Generated by Django 6.0.4 on 2026-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_perfilusuario_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite de acceso. Null significa acceso permanente.', null=True),
        ),
    ]
