# Generated by Django 6.0.4 on 2026-09-08 19:31

import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0020_alter_perfilusuario_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario.', null=True, upload_to=finanzas.models.foto_perfil_upload_to),
        ),
    ]
