# Generated by Django 6.0.4 on 2026-09-08 20:01

import finanzas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0021_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_original',
            field=models.ImageField(blank=True, help_text='Foto original completa sin recortar.', null=True, upload_to=finanzas.models.foto_original_upload_to),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil recortada del usuario.', null=True, upload_to=finanzas.models.foto_perfil_upload_to),
        ),
    ]
