# Generated by Django 6.0.4 on 2026-09-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_perfilusuario_foto_original_alter_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
