# Generated by Django 6.0.4 on 2026-09-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_presupuesto_fecha_fin_presupuesto_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
