# Generated by Django 6.0.4 on 2026-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0024_alter_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='es_google',
            field=models.BooleanField(default=False, help_text='Indica si el usuario se autentica mediante Google OAuth.'),
        ),
    ]
