# Generated by Django 6.0.4 on 2026-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0025_perfilusuario_es_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_google',
            field=models.URLField(blank=True, help_text='URL directa de la foto de perfil provista por Google OAuth.', max_length=500, null=True),
        ),
    ]
