# Generated by Django 6.0.4 on 2026-09-15 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0026_perfilusuario_foto_google'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoIaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('total_mensajes', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso diario de IA',
                'verbose_name_plural': 'Usos diarios de IA',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='uniq_usuario_fecha_uso_ia')],
            },
        ),
    ]
